# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SpectraViewGUI.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(792, 589)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(25, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.toolBar1 = QtWidgets.QWidget(self.tab)
        self.toolBar1.setMinimumSize(QtCore.QSize(25, 0))
        self.toolBar1.setMaximumSize(QtCore.QSize(16777215, 30))
        self.toolBar1.setObjectName("toolBar1")
        self.horizontalLayout_2.addWidget(self.toolBar1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.ImagMin = QtWidgets.QLineEdit(self.tab)
        self.ImagMin.setMaximumSize(QtCore.QSize(50, 16777215))
        self.ImagMin.setObjectName("ImagMin")
        self.horizontalLayout_2.addWidget(self.ImagMin)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.ImagMax = QtWidgets.QLineEdit(self.tab)
        self.ImagMax.setMaximumSize(QtCore.QSize(50, 16777215))
        self.ImagMax.setObjectName("ImagMax")
        self.horizontalLayout_2.addWidget(self.ImagMax)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.mpl1 =  MatplotlibWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl1.sizePolicy().hasHeightForWidth())
        self.mpl1.setSizePolicy(sizePolicy)
        self.mpl1.setObjectName("mpl1")
        self.verticalLayout.addWidget(self.mpl1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.toolBar2 = QtWidgets.QWidget(self.tab_2)
        self.toolBar2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.toolBar2.setObjectName("toolBar2")
        self.horizontalLayout_5.addWidget(self.toolBar2)
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_5.addWidget(self.label_14)
        self.ProyMin = QtWidgets.QLineEdit(self.tab_2)
        self.ProyMin.setMaximumSize(QtCore.QSize(50, 16777215))
        self.ProyMin.setObjectName("ProyMin")
        self.horizontalLayout_5.addWidget(self.ProyMin)
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_5.addWidget(self.label_16)
        self.ProyMax = QtWidgets.QLineEdit(self.tab_2)
        self.ProyMax.setMaximumSize(QtCore.QSize(50, 16777215))
        self.ProyMax.setObjectName("ProyMax")
        self.horizontalLayout_5.addWidget(self.ProyMax)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.mpl2 =  MatplotlibWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl2.sizePolicy().hasHeightForWidth())
        self.mpl2.setSizePolicy(sizePolicy)
        self.mpl2.setObjectName("mpl2")
        self.verticalLayout_2.addWidget(self.mpl2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.toolBar1_2 = QtWidgets.QWidget(self.tab_6)
        self.toolBar1_2.setMinimumSize(QtCore.QSize(25, 0))
        self.toolBar1_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.toolBar1_2.setObjectName("toolBar1_2")
        self.horizontalLayout_6.addWidget(self.toolBar1_2)
        self.label_9 = QtWidgets.QLabel(self.tab_6)
        self.label_9.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.ImagMin_2 = QtWidgets.QLineEdit(self.tab_6)
        self.ImagMin_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.ImagMin_2.setObjectName("ImagMin_2")
        self.horizontalLayout_6.addWidget(self.ImagMin_2)
        self.label_10 = QtWidgets.QLabel(self.tab_6)
        self.label_10.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.ImagMax_2 = QtWidgets.QLineEdit(self.tab_6)
        self.ImagMax_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.ImagMax_2.setObjectName("ImagMax_2")
        self.horizontalLayout_6.addWidget(self.ImagMax_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.mpl3 =  MatplotlibWidget(self.tab_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl3.sizePolicy().hasHeightForWidth())
        self.mpl3.setSizePolicy(sizePolicy)
        self.mpl3.setObjectName("mpl3")
        self.verticalLayout_4.addWidget(self.mpl3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.acuFreeze = QtWidgets.QPushButton(self.tab_6)
        self.acuFreeze.setObjectName("acuFreeze")
        self.horizontalLayout_7.addWidget(self.acuFreeze)
        self.acuRestart = QtWidgets.QPushButton(self.tab_6)
        self.acuRestart.setObjectName("acuRestart")
        self.horizontalLayout_7.addWidget(self.acuRestart)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.tabWidget.addTab(self.tab_6, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setMinimumSize(QtCore.QSize(0, 18))
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.ExposureEdit = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.ExposureEdit.setReadOnly(True)
        self.ExposureEdit.setDecimals(3)
        self.ExposureEdit.setMinimum(0.001)
        self.ExposureEdit.setMaximum(9999.99)
        self.ExposureEdit.setObjectName("ExposureEdit")
        self.verticalLayout_3.addWidget(self.ExposureEdit)
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_3.addWidget(self.label_17)
        self.ImageModeBox = QtWidgets.QComboBox(self.tab_3)
        self.ImageModeBox.setEnabled(False)
        self.ImageModeBox.setObjectName("ImageModeBox")
        self.verticalLayout_3.addWidget(self.ImageModeBox)
        self.label_32 = QtWidgets.QLabel(self.tab_3)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_3.addWidget(self.label_32)
        self.ReadoutModeBox = QtWidgets.QComboBox(self.tab_3)
        self.ReadoutModeBox.setEnabled(False)
        self.ReadoutModeBox.setObjectName("ReadoutModeBox")
        self.verticalLayout_3.addWidget(self.ReadoutModeBox)
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setMinimumSize(QtCore.QSize(0, 18))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.AcuEdit = QtWidgets.QSpinBox(self.tab_3)
        self.AcuEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.AcuEdit.setMaximumSize(QtCore.QSize(100, 25))
        self.AcuEdit.setReadOnly(True)
        self.AcuEdit.setMinimum(0)
        self.AcuEdit.setObjectName("AcuEdit")
        self.verticalLayout_3.addWidget(self.AcuEdit)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        self.StartButton = QtWidgets.QPushButton(self.tab_3)
        self.StartButton.setMaximumSize(QtCore.QSize(600, 16777215))
        self.StartButton.setObjectName("StartButton")
        self.verticalLayout_7.addWidget(self.StartButton)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem)
        self.LockBox = QtWidgets.QCheckBox(self.tab_3)
        self.LockBox.setObjectName("LockBox")
        self.verticalLayout_7.addWidget(self.LockBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.HHGButton = QtWidgets.QPushButton(self.tab_3)
        self.HHGButton.setObjectName("HHGButton")
        self.verticalLayout_7.addWidget(self.HHGButton)
        self.pushButton = QtWidgets.QPushButton(self.tab_3)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_7.addWidget(self.pushButton)
        self.PumpButton = QtWidgets.QPushButton(self.tab_3)
        self.PumpButton.setObjectName("PumpButton")
        self.verticalLayout_7.addWidget(self.PumpButton)
        self.BgButton_2 = QtWidgets.QPushButton(self.tab_3)
        self.BgButton_2.setObjectName("BgButton_2")
        self.verticalLayout_7.addWidget(self.BgButton_2)
        self.EntryButton = QtWidgets.QPushButton(self.tab_3)
        self.EntryButton.setObjectName("EntryButton")
        self.verticalLayout_7.addWidget(self.EntryButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_15 = QtWidgets.QLabel(self.tab_5)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_8.addWidget(self.label_15)
        self.MemorzView = QtWidgets.QListView(self.tab_5)
        self.MemorzView.setObjectName("MemorzView")
        self.verticalLayout_8.addWidget(self.MemorzView)
        self.AddButton = QtWidgets.QPushButton(self.tab_5)
        self.AddButton.setObjectName("AddButton")
        self.verticalLayout_8.addWidget(self.AddButton)
        self.LoadButton = QtWidgets.QPushButton(self.tab_5)
        self.LoadButton.setObjectName("LoadButton")
        self.verticalLayout_8.addWidget(self.LoadButton)
        self.RemoveButton = QtWidgets.QPushButton(self.tab_5)
        self.RemoveButton.setObjectName("RemoveButton")
        self.verticalLayout_8.addWidget(self.RemoveButton)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_12 = QtWidgets.QLabel(self.tab_7)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_4.addWidget(self.label_12)
        self.NumImgEdit = QtWidgets.QSpinBox(self.tab_7)
        self.NumImgEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.NumImgEdit.setMinimum(1)
        self.NumImgEdit.setMaximum(200)
        self.NumImgEdit.setObjectName("NumImgEdit")
        self.horizontalLayout_4.addWidget(self.NumImgEdit)
        self.saveAcuBox = QtWidgets.QCheckBox(self.tab_7)
        self.saveAcuBox.setObjectName("saveAcuBox")
        self.horizontalLayout_4.addWidget(self.saveAcuBox)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.label_11 = QtWidgets.QLabel(self.tab_7)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_9.addWidget(self.label_11)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.PathEdit = QtWidgets.QLineEdit(self.tab_7)
        self.PathEdit.setObjectName("PathEdit")
        self.horizontalLayout_3.addWidget(self.PathEdit)
        self.PathButton = QtWidgets.QPushButton(self.tab_7)
        self.PathButton.setMaximumSize(QtCore.QSize(20, 16777215))
        self.PathButton.setObjectName("PathButton")
        self.horizontalLayout_3.addWidget(self.PathButton)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        self.label_13 = QtWidgets.QLabel(self.tab_7)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_9.addWidget(self.label_13)
        self.NameEdit = QtWidgets.QLineEdit(self.tab_7)
        self.NameEdit.setObjectName("NameEdit")
        self.verticalLayout_9.addWidget(self.NameEdit)
        self.label_18 = QtWidgets.QLabel(self.tab_7)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_9.addWidget(self.label_18)
        self.dataSetEdit = QtWidgets.QLineEdit(self.tab_7)
        self.dataSetEdit.setObjectName("dataSetEdit")
        self.verticalLayout_9.addWidget(self.dataSetEdit)
        self.label_19 = QtWidgets.QLabel(self.tab_7)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_9.addWidget(self.label_19)
        self.CommentTextEdit = QtWidgets.QPlainTextEdit(self.tab_7)
        self.CommentTextEdit.setObjectName("CommentTextEdit")
        self.verticalLayout_9.addWidget(self.CommentTextEdit)
        self.SaveButton = QtWidgets.QPushButton(self.tab_7)
        self.SaveButton.setMaximumSize(QtCore.QSize(600, 16777215))
        self.SaveButton.setObjectName("SaveButton")
        self.verticalLayout_9.addWidget(self.SaveButton)
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.groupBox = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_11.setContentsMargins(1, -1, 1, 1)
        self.horizontalLayout_11.setSpacing(4)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_30 = QtWidgets.QLabel(self.groupBox)
        self.label_30.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_30.setObjectName("label_30")
        self.verticalLayout_16.addWidget(self.label_30)
        self.Y0Edit = QtWidgets.QLineEdit(self.groupBox)
        self.Y0Edit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.Y0Edit.setReadOnly(True)
        self.Y0Edit.setObjectName("Y0Edit")
        self.verticalLayout_16.addWidget(self.Y0Edit)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_8.setObjectName("label_8")
        self.verticalLayout_16.addWidget(self.label_8)
        self.Y1Edit = QtWidgets.QLineEdit(self.groupBox)
        self.Y1Edit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.Y1Edit.setReadOnly(True)
        self.Y1Edit.setObjectName("Y1Edit")
        self.verticalLayout_16.addWidget(self.Y1Edit)
        self.label_31 = QtWidgets.QLabel(self.groupBox)
        self.label_31.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_31.setObjectName("label_31")
        self.verticalLayout_16.addWidget(self.label_31)
        self.YBinningEdit = QtWidgets.QLineEdit(self.groupBox)
        self.YBinningEdit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.YBinningEdit.setReadOnly(True)
        self.YBinningEdit.setObjectName("YBinningEdit")
        self.verticalLayout_16.addWidget(self.YBinningEdit)
        self.horizontalLayout_11.addLayout(self.verticalLayout_16)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_13.addWidget(self.label_5)
        self.X0Edit = QtWidgets.QLineEdit(self.groupBox)
        self.X0Edit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.X0Edit.setReadOnly(True)
        self.X0Edit.setObjectName("X0Edit")
        self.verticalLayout_13.addWidget(self.X0Edit)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_6.setObjectName("label_6")
        self.verticalLayout_13.addWidget(self.label_6)
        self.X1Edit = QtWidgets.QLineEdit(self.groupBox)
        self.X1Edit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.X1Edit.setReadOnly(True)
        self.X1Edit.setObjectName("X1Edit")
        self.verticalLayout_13.addWidget(self.X1Edit)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_7.setObjectName("label_7")
        self.verticalLayout_13.addWidget(self.label_7)
        self.XBinningEdit = QtWidgets.QLineEdit(self.groupBox)
        self.XBinningEdit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.XBinningEdit.setReadOnly(True)
        self.XBinningEdit.setObjectName("XBinningEdit")
        self.verticalLayout_13.addWidget(self.XBinningEdit)
        self.horizontalLayout_11.addLayout(self.verticalLayout_13)
        self.horizontalLayout_10.addWidget(self.groupBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_20.setObjectName("label_20")
        self.verticalLayout_10.addWidget(self.label_20)
        self.PreAmpBox = QtWidgets.QComboBox(self.groupBox_2)
        self.PreAmpBox.setObjectName("PreAmpBox")
        self.verticalLayout_10.addWidget(self.PreAmpBox)
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_21.setObjectName("label_21")
        self.verticalLayout_10.addWidget(self.label_21)
        self.ADCBox = QtWidgets.QComboBox(self.groupBox_2)
        self.ADCBox.setObjectName("ADCBox")
        self.verticalLayout_10.addWidget(self.ADCBox)
        self.label_22 = QtWidgets.QLabel(self.groupBox_2)
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_22.setObjectName("label_22")
        self.verticalLayout_10.addWidget(self.label_22)
        self.dTypeBox = QtWidgets.QComboBox(self.groupBox_2)
        self.dTypeBox.setObjectName("dTypeBox")
        self.verticalLayout_10.addWidget(self.dTypeBox)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.horizontalLayout.addWidget(self.tabWidget_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 792, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.tabWidget_2.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Min:"))
        self.label_4.setText(_translate("MainWindow", "Max:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Image"))
        self.label_14.setText(_translate("MainWindow", "Min:"))
        self.label_16.setText(_translate("MainWindow", "Max:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Proyection"))
        self.label_9.setText(_translate("MainWindow", "Min:"))
        self.label_10.setText(_translate("MainWindow", "Max:"))
        self.acuFreeze.setText(_translate("MainWindow", "Freeze"))
        self.acuRestart.setText(_translate("MainWindow", "Restart"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Acum mode"))
        self.label.setText(_translate("MainWindow", "Exposure"))
        self.label_17.setText(_translate("MainWindow", "Image Mode"))
        self.label_32.setText(_translate("MainWindow", "Readout Mode"))
        self.label_3.setText(_translate("MainWindow", "Acumulations"))
        self.StartButton.setText(_translate("MainWindow", "StartAcq"))
        self.LockBox.setText(_translate("MainWindow", "Lockin Mode"))
        self.HHGButton.setText(_translate("MainWindow", "HHG shutter (Open) "))
        self.pushButton.setText(_translate("MainWindow", "Pulse valve (Open)"))
        self.PumpButton.setText(_translate("MainWindow", "Pump shutter (Open)"))
        self.BgButton_2.setText(_translate("MainWindow", "Take Bg"))
        self.EntryButton.setText(_translate("MainWindow", "&Make entry"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Acq. Conf."))
        self.label_15.setText(_translate("MainWindow", "Saved images:"))
        self.AddButton.setText(_translate("MainWindow", "Add"))
        self.LoadButton.setText(_translate("MainWindow", "Load"))
        self.RemoveButton.setText(_translate("MainWindow", "Remove"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Memory"))
        self.label_12.setText(_translate("MainWindow", "Save Images:"))
        self.saveAcuBox.setText(_translate("MainWindow", "Save Acu"))
        self.label_11.setText(_translate("MainWindow", "Saving path:"))
        self.PathButton.setText(_translate("MainWindow", "..."))
        self.label_13.setText(_translate("MainWindow", "File name:"))
        self.label_18.setText(_translate("MainWindow", "Data Set"))
        self.label_19.setText(_translate("MainWindow", "Comments"))
        self.SaveButton.setText(_translate("MainWindow", "Save"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "Saving"))
        self.groupBox.setTitle(_translate("MainWindow", "ROI"))
        self.label_30.setText(_translate("MainWindow", "Y0:"))
        self.label_8.setText(_translate("MainWindow", "Size Y:"))
        self.label_31.setText(_translate("MainWindow", "Binning Y:"))
        self.label_5.setText(_translate("MainWindow", "X0:"))
        self.label_6.setText(_translate("MainWindow", "Size X:"))
        self.label_7.setText(_translate("MainWindow", "Binning X:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Digitalization"))
        self.label_20.setText(_translate("MainWindow", "PreAmpG:"))
        self.label_21.setText(_translate("MainWindow", "ADC Speed:"))
        self.label_22.setText(_translate("MainWindow", "Data type:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Others"))

from .mplwidget import  MatplotlibWidget
